# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='a',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 21, 13, 40, 54, 333916, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='a',
            name='editable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='b',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 21, 13, 41, 9, 717742, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b',
            name='editable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='c',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 21, 13, 41, 18, 526245, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c',
            name='editable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='d',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 21, 13, 41, 23, 725769, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d',
            name='editable',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
