# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='a_field',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b',
            name='a_field',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c',
            name='a_field',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d',
            name='a_field',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
