# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classlist', '0003_auto_20170221_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a',
            options={'verbose_name': 'A-Form'},
        ),
        migrations.AlterModelOptions(
            name='b',
            options={'verbose_name': 'B-Form'},
        ),
        migrations.AlterModelOptions(
            name='c',
            options={'verbose_name': 'C-Form'},
        ),
        migrations.AlterModelOptions(
            name='d',
            options={'verbose_name': 'D-Form'},
        ),
    ]
